applicant:
  get:
    endpoint: "http://localhost:8082/sagaloandemo/crud/applicant"
  update:
    endpoint: "http://localhost:8082/sagaloandemo/crud/applicant"

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.springframework.security: debug

server:
  port: 8083
  servlet:
    context-path: /sagaloandemo/applicant
