loan:
  create:
    endpoint: "http://loan-demo-model.apps.cluster-gfd2c.gfd2c.sandbox425.opentlc.com/sagaloandemo/crud/loan"
  delete:
    endpoint: "http://loan-demo-model.apps.cluster-gfd2c.gfd2c.sandbox425.opentlc.com/sagaloandemo/crud/loan"

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.springframework.security: debug

server:
  port: 8080
  servlet:
    context-path: /
